### ISSUE TITLE
Incorrect bower.json dependency

### ISSUE THREAD

**Issue by sccrgoalie1** [DevExpress/bower-xtrareports-js#1]
Hello,

The bower.json dependency of devextreme 17.1.2 does not allow this to install.  Please change it to 17.1.2-beta.

**Comment by Kochkin** [comment]
Thank you for pointing out the issue. Please use the '**17.1.2-beta.1**' tag to get all resources properly:
`bower install xtrareportsjs#17.1.2-beta.1`
