### ISSUE TITLE
JQuery Dependencies

### ISSUE THREAD

**Issue by mike-card** [DevExpress/bower-xtrareports-js#2]
The jquery dependencies need to be updated to match the main devextreme bower package:
jquery#^2.2.3 || ^3.0.0

Everything seems to run fine with the report package and jquery 3.

Thanks!

**Comment by Kochkin** [comment]
Thank you for pointing out this discrepancy.
To fix this on your side immediately, you can use **resolutions** directive to force bower to download the latest version.
```
"resolutions": {
    "jquery": "^3.0.0"
  }
```

I have updated this dependency, and I would appreciate it if you create a new issue in case of a bugs related to the jQuery 3.0

Thanks
